export type ServiceStatus =
  | 'AGUARDANDO_COLETA'
  | 'EM_TRANSITO_PARA_ESTETICA'
  | 'RECEBIDO_NA_ESTETICA'
  | 'EM_LAVAGEM_SERVICO'
  | 'PRONTO_PARA_DEVOLUCAO'
  | 'EM_TRANSITO_PARA_ENTREGA'
  | 'ENTREGUE_CONCLUIDO';

export const STATUS_ORDER: ServiceStatus[] = [
  'AGUARDANDO_COLETA',
  'EM_TRANSITO_PARA_ESTETICA',
  'RECEBIDO_NA_ESTETICA',
  'EM_LAVAGEM_SERVICO',
  'PRONTO_PARA_DEVOLUCAO',
  'EM_TRANSITO_PARA_ENTREGA',
  'ENTREGUE_CONCLUIDO',
];

export const STATUS_LABELS: Record<ServiceStatus, string> = {
  AGUARDANDO_COLETA: 'Aguardando Coleta',
  EM_TRANSITO_PARA_ESTETICA: 'Em Trânsito para Estética',
  RECEBIDO_NA_ESTETICA: 'Recebido na Estética',
  EM_LAVAGEM_SERVICO: 'Em Lavagem/Serviço',
  PRONTO_PARA_DEVOLUCAO: 'Pronto para Devolução',
  EM_TRANSITO_PARA_ENTREGA: 'Em Trânsito para Entrega',
  ENTREGUE_CONCLUIDO: 'Entregue/Concluído',
};
